import { siteConfig, absoluteUrl } from "@/lib/site";

/**
 * Build a Next.js `metadata` object with consistent SEO defaults.
 *
 * @param {object} options
 * @param {string} options.title          Page title (without the site suffix)
 * @param {string} options.description    Meta description (aim for 120-160 chars)
 * @param {string} options.path           Canonical path, e.g. "/about"
 * @param {string} [options.image]        Absolute or root-relative OG image URL
 * @param {string} [options.type]         Open Graph type ("website" | "article" | "profile")
 * @param {boolean} [options.noIndex]     Exclude the page from search engines
 * @param {boolean} [options.absoluteTitle] Use the title as-is (skip the "%s | Site" template)
 */
/** Generated by app/opengraph-image.js (1200x630, brand colours + logo). */
export const DEFAULT_OG_IMAGE = "/opengraph-image";

export function buildMetadata({
  title,
  description,
  path = "/",
  image = DEFAULT_OG_IMAGE,
  type = "website",
  noIndex = false,
  absoluteTitle = false,
}) {
  const url = absoluteUrl(path);
  const ogImage = image ? absoluteUrl(image) : undefined;

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title: absoluteTitle || !title ? title || siteConfig.name : `${title} | ${siteConfig.name}`,
      description,
      url,
      siteName: siteConfig.name,
      locale: siteConfig.locale,
      type,
      ...(ogImage
        ? { images: [image === DEFAULT_OG_IMAGE ? { url: ogImage, width: 1200, height: 630, alt: title } : { url: ogImage, alt: title }] }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: absoluteTitle || !title ? title || siteConfig.name : `${title} | ${siteConfig.name}`,
      description,
      ...(ogImage ? { images: [ogImage] } : {}),
    },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
  };
}
